USE DB_UDBH
GO

--Fix dirty read--
--T2--
CREATE PROC sp_XemDonHang_TaiXe
	@ID_TaiXe CHAR(10)
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM DON_HANG WHERE ID_TaiXe = @ID_TaiXe
COMMIT TRAN
RETURN
GO

EXEC sp_XemDonHang_TaiXe 'TX03'
