USE DB_UDBH
GO

--T2--
CREATE PROC sp_XemDonHang_TaiXe
	@ID_TaiXe CHAR(10)
AS
SET TRANSACTION ISOLATION
LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM DON_HANG WHERE ID_TaiXe = @ID_TaiXe
COMMIT TRAN
RETURN
GO
--EXEC--
EXEC sp_XemDonHang_TaiXe 'TX03'
DROP PROC sp_XemDonHang_TaiXe

